[versions]
androidGradlePlugin = "8.6.0-rc01"
kotlin = "2.0.10"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.5"
activityCompose = "1.9.1"
composeBom = "2024.06.00"
appcompat = "1.7.0"
material = "1.12.0"
androidDesugarJdkLibs = "2.0.4"
dagger = "2.51.1"
daggerHiltNavigationCompose = "1.2.0"
ksp = "2.0.10-1.0.24"
detekt = "1.23.7"
twitterComposeRule = "0.0.26"
ktorfit = "2.1.0"

[libraries]
androidxCoreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidxJunit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidxEspressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidxLifecycleRuntimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidxLifecycleRuntimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
composeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
composeUi = { group = "androidx.compose.ui", name = "ui" }
composeUiGraphics = { group = "androidx.compose.ui", name = "ui-graphics" }
composeUiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
composeUiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
composeUiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
composeUiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
composeMaterial3 = { group = "androidx.compose.material3", name = "material3" }
androidxAppcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
composeCompilerGradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
javaPoet = { module = "com.squareup:javapoet", version = "1.13.0" }

androidGradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
androidDesugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
hiltGradlePlugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "dagger" }
hiltNavigationComposePlugin = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "daggerHiltNavigationCompose" }
kspGradlePlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
detektGradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
detektFormatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
twitterComposeRule = { module = "com.twitter.compose.rules:detekt", version.ref = "twitterComposeRule" }
ktorfitGradlePlugin = { module = "de.jensklingenberg.ktorfit:gradle-plugin", version.ref = "ktorfit" }
kotlinxSerializationGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
daggerHiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
daggerHiltAndroidCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }

[plugins]
androidGradlePlugin = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidGradleLibraryPlugin = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlinGradlePlugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
# kotlin 2.0からトップレベルのgradleでインストールする必要がある
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hiltGradlePlugin = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kspGradlePlugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detektGradlePlugin = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }


[bundles]
plugins = [
    "androidGradlePlugin",
    "kotlinGradlePlugin",
    "composeCompilerGradlePlugin",
    "hiltGradlePlugin",
    "kspGradlePlugin",
    #    "ktorfitGradlePlugin",  2.1.0が見つからないと出るため一旦コメントアウト
    "kotlinxSerializationGradlePlugin",
    "detektGradlePlugin",
    "twitterComposeRule",
]